config/routes.rb
Rails.application.routes.draw do
  # mount Attachinary::Engine => "/attachinary"
  root to: "cocktails#index"
  # root to: "cocktails#new"
  # get 'ingredients/name'
  # get 'cocktails/name'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "controller#index"
  # resources :cocktails, only [:show, :index, :new, :create]
  resources :cocktails, only: [:show, :index, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :ingredients, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @new_dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    cocktail = Cocktail.find(params[id])
    cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  # end

  def create
    @dose = Dose.new(dose_params)
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      flash[:error] = @dose.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
   def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<!-- <html>
<head>
<title>youR CockTail SlaVe</title>
</head>
<body>




<div class="main">
  <div class="wrap">
    content and sidebar are swapped. They can be made to show in the order above with CSS
    <div class="content"></div>
    <div class="sidebar"></div>
  </div>
</div>

 -->

<div class="container">
  <div class ="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <h2>Find a cocktail you like</h2>
      <ol>
      <% @cocktails.each do |cocktail| %>
        <li><%= link_to cocktail.name, cocktail_path(cocktail)%></li>
      <% end %>
      </ol>

      <%= link_to "Create new cocktail", new_cocktail_path %>
    </div>
  </div>
</div>



<!-- <footer>
  <div class="wrap">
    <div class="sidebar"></div>
    <div class="content"></div>
  </div>
</footer>

</body>
</html>
 -->

app/views/cocktails/new.html.erb
<div class="container">
  <div class ="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
        <%= link_to "Back", cocktails_path %>

      <ul>
          <% @cocktail.doses.each do |dose| %>
          <li>
          <%= dose.description %> of <%= dose.ingredient.name %>
          (<%= link_to "delete", dose_path(dose), method: :delete %>)
          </li>
         <% end %>
      </ul>

    <%= simple_form_for @cocktail do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>


    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class ="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
        <%= link_to "Overview", cocktails_path %>

      <ul>
          <% @cocktail.doses.each do |dose| %>
          <li>
          <%= dose.description %> of <%= dose.ingredient.name %>
          (<%= link_to "delete", dose_path(dose), method: :delete %>)
          </li>
         <% end %>
      </ul>

    <%= simple_form_for [@cocktail, @new_dose], url: cocktail_doses_path(@cocktail) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description %>
  <%= f.hidden_field :cocktail_id, value: @cocktail.id %>

  <%= f.input :ingredient_id, collection: Ingredient.all.map{|i| [i.name, i.id] } %>
   <%= f.button :submit %>
<% end %>


    </div>
  </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose], url: cocktail_doses_path do |f| %>
  <%= f.error_notification %>

  <%= f.input :description %>
  <%= f.hidden_field :cocktail_id, value: @cocktail.id %>

  <%= f.input :ingredient_id, collection: Ingredient.all.map{|i| [i.name, i.id] } %>
   <%= f.button :submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1>Details about <%= @ingredient.name %></h1>

<p>Here are the Cocktails you are able to make:</p>

<ul>
  <% ingredient.cocktails.each do |cocktail| %>
    <li><%= cocktail.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= cloudinary_js_config %>
  </head>

  <body>

    <%=  render "shared/navbar" %>
    <% flash.each do |key, value| %>
      <div class="alert"><%= content_tag :div, value, class: "flash #{key}" %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/navbar_wagon.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>